---
pvepass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35643839643131663835353038643663393839353932623832646462636366336262653865336630
          3863323665313430633266626335383331646561353130650a346331626336333234386538356165
          62333263313065353332316332353162333964636434643264353933396437323164336261616564
          6461326263643465320a393737333434316463643734393234663665656436623663623831666432
          6338
public_network: 192.168.1.0/24
ceph_osd_disk: /dev/nvme0n1p4
ceph_part_start: 537GB
pool_name: mypool
terraform_prov_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30636239313663326331653937623335303133343962643865653362316230363030316238323839
          3138623330366234303135616463343266353532343161630a626435633161656431306634663533
          32643362396239666638623261646361326236313962353964313331313464646239303462616165
          6137303537383533640a383562323634326437666466366364663337336335653137383766646637
          33386261396135636364373438393833316637393464353830306665613939363264
