---
packages:
  - vim
  - parted
  - prometheus-node-exporter

ceph_packages:
  - ceph
  - ceph-common
  - ceph-fuse
  - ceph-mds
  - ceph-volume
  - jq
  - gdisk
  - nvme-cli

remove_repos:
  - /etc/apt/sources.list.d/pve-enterprise.sources
